In [110]:
# Imports
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.optimize
import random
from sklearn import svm
import ast

#import patsy
#import statsmodels.api as sm
#import scipy.stats as stats
#from scipy.stats import ttest_ind, chisquare, normaltest

In [111]:
import urllib.request
def parseData(fname):
	for l in urllib.request.urlopen(fname):
		yield eval(l)
data = list(parseData("http://jmcauley.ucsd.edu/cse258/data/beer/beer_50000.json"))

In [186]:
# data
####

#######################################################################        
######                     QUESTION 1                           
#######################################################################

In [199]:
lst1 = []
one_star_ratings = 0
two_star_ratings = 0
three_star_ratings = 0
four_star_ratings = 0
five_star_ratings = 0

for i in data:
    for x,y in i.items():
        if x == "review/taste":
            lst1.append(y)
            
for i in lst1:
    if i >= 1.0 and i < 2.0:
        one_star_ratings = one_star_ratings + 1
    elif i >= 2.0 and i < 3.0:
        two_star_ratings = two_star_ratings + 1
    elif i >= 3.0 and i < 4.0:
        three_star_ratings = three_star_ratings + 1
    elif i >= 4.0 and i < 5.0:
        four_star_ratings = four_star_ratings + 1
    elif i >= 5.0:
        five_star_ratings = five_star_ratings + 1
        

In [200]:
print("# of one star ratings: %s" % one_star_ratings)  # of 1 star ratings = 201
print("# of two star ratings: %s" % two_star_ratings)  # of 2 star ratings = 1099
print("# of three star ratings: %s" % three_star_ratings)  # of 3 star ratings = 4137
print("# of four star ratings: %s" % four_star_ratings)  # of 3 star ratings = 4137
print("# of five star ratings: %s" % five_star_ratings)  # of 3 star ratings = 4137

# of one star ratings: 554
# of two star ratings: 2723
# of three star ratings: 12934
# of four star ratings: 29458
# of five star ratings: 4331


#######################################################################        
######                      QUESTION 2                           #
#######################################################################        

In [311]:
#data

In [218]:
# Get all beers (including mulitple occurances) into a list

list_of_all_beers = [d['beer/name'] for d in data]

In [312]:
# Print out all beers including multiple occurances

#list_of_all_beers

In [272]:
len(list_of_all_beers)

50000

In [220]:
unique_list = set(list_of_all_beers)

In [313]:
#unique_list

In [222]:
len(unique_list)

1872

In [223]:
beers_unique = [[x,list_of_all_beers.count(x)] for x in set(list_of_all_beers)]

In [314]:
#beers_unique

In [244]:
len(beers_unique)

1872

In [273]:
# Dictionary of all beers with at least 5 reviews (unique)

list6 = []
list7 = []
for i in beers_unique:
    if i[1] >= 5:
        list6.append(i[0])
        list7.append(i[1])

In [274]:
print(len(list6))
print(len(list7))

647
647


In [315]:
# list of all beers with at least 5 reviews

at_least_5 = list(zip(list6, list7))
#at_least_5

In [262]:
# Dictionary of all beers and their review/taste

list1 = []
list2 = []
for i in data:
    for a,b in i.items():
        for c,d in i.items():
            if a == 'beer/name':
                if c == 'review/taste':
                    list1.append(b)
                    list2.append(d)

In [263]:
print(len(list1))
print(len(list2))

50000
50000


In [264]:
beer_name_taste = list(zip(list1, list2))

In [316]:
#beer_name_taste

In [266]:
len(beer_name_taste)

50000

In [268]:
list3 = []
list4 = []
for a,b in diction1.items():
    count = 0
    for c in beer_name_taste:
        if c[0] == a:
            count += c[1]
    list3.append(a)
    list4.append(count)
    

In [269]:
print(len(list3))
print(len(list4))

647
647


In [270]:
# List of beers with all their reviews/taste ratings added together

combined = list(zip(list3, list4))

In [317]:
#combined

In [276]:
list8 = []
list9 = []
for i in at_least_5:
    for j in combined:
        if j[0] == i[0]:
            list8.append(i[0])
            list9.append(j[1] / i[1])

In [277]:
print(len(list8))
print(len(list9))

647
647


In [318]:
# Averages
avg = list(zip(list8, list9))
#avg

In [279]:
# Higest averages
maximum = 0
for i in avg:
    if i[1] >= maximum:
        maximum = i[1]
maximum

4.6970172684458396

In [280]:
# Find if other beers also have same highest rating for review/taste
list11 = []
for i in avg:
    if i[1] == maximum:
        list11.append(i[0])
list11

['Founders CBS Imperial Stout']

In [281]:
# Print out highest average rated beer and its average
print("Highest average rated beer (review/taste): %s" % list11[0])
print("Highest average: %s" % maximum)

Highest average rated beer (review/taste): Founders CBS Imperial Stout
Highest average: 4.6970172684458396


In [124]:
len(data)

50000

In [125]:
lst3 = []
for i in range(len(data)):
    lst3.append(1)
    
len(lst3)

50000

In [126]:
lst4 = []

for i in data:
    for x,y in i.items():
        if x == 'beer/style':
            lst4.append(y)

#lst4


In [127]:
lst6 = []
for i in lst4:
    if i == 'Hefeweizen':
        lst6.append(1)
    else:
        lst6.append(0)
        
lst6.count(1)

618

In [128]:
lst5 = []
for i in data:
    for x,y in i.items():
        if x == 'beer/ABV':
            lst5.append(y)
     
    
#lst5

In [319]:
X = list(zip(lst3,lst6,lst5))
#X

In [130]:
y = [d['review/taste'] for d in data]

In [131]:
len(y)

50000

In [132]:
theta,residuals,rank,s = np.linalg.lstsq(X, y)

D:\ProgramFiles\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


#######################################################################        
                     QUESTION 3            
#######################################################################



theta_0 = indicates the average review/taste. <br>
theta_1 = indicates the difference between the average review/taste when beer/ABV is 0. <br>
theta_2 = indicates the difference between the average review/taste when beer is not Hefeweizen (0).  <br>

In [214]:
# Theta values for theta 0, theta 1, and theta 2
print("theta_0: %s" % theta[0])
print("theta_1: %s" % theta[1])
print("theta_2: %s" % theta[2])

theta_0: 3.1179508424741784
theta_1: -0.05637405770379309
theta_2: 0.10877901639208253


#####################################################################
<br>                           Question 4 
#####################################################################

In [134]:
# Split the original dataset in half
data_1 = data[:len(data)//2] # training set
data_2 = data[len(data)//2:] # test set

In [135]:
def get_col_1(d):
    temp_lst1 = []
    
    for i in range(len(d)):
        temp_lst1.append(1)
        
    return temp_lst1

In [136]:
def get_col_2(d):
    temp_lst = []

    for i in d:
        for x,y in i.items():
            if x == 'beer/style':
                temp_lst.append(y)

    temp_lst2 = []
    for i in temp_lst:
        if i == 'Hefeweizen':
            temp_lst2.append(1)
        else:
            temp_lst2.append(0)
    
    return temp_lst2
        
      

In [137]:
def get_col_3(d):
    temp_lst = []
    
    for i in d:
        for x,y in i.items():
            if x == 'beer/ABV':
                temp_lst.append(y)
     
    return temp_lst

In [138]:
def get_X(d):
    
    X = list(zip(get_col_1(d), get_col_2(d), get_col_3(d)))
    
    return X
    

In [139]:
def get_y(d):
    
    y = [da['review/taste'] for da in d]
    
    return y

In [140]:
def get_thetas(d):
    
    X = get_X(d)
    y = get_y(d)
    
    theta,residuals,rank,s = np.linalg.lstsq(X, y)
    
    return theta

In [293]:
# verify get functions work on original data
a = get_thetas(data)
a

D:\ProgramFiles\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


array([ 3.11795084, -0.05637406,  0.10877902])

In [294]:
a

array([ 3.11795084, -0.05637406,  0.10877902])

In [142]:
def get_MSE(ratings, predictions):
    
    mse = 0
    
    for r, p in zip(ratings, predictions):
        mse = mse + (r - p)**2
        
    return (mse / len(ratings))

In [143]:
def get_ratings(d):
    tmp_lst = []
    
    for i in d:
        for x,y in i.items():
            if x == 'review/taste':
                tmp_lst.append(y)
                
    return tmp_lst

In [286]:
#X = get_X(data_1)
#X

In [295]:
def apply_new_model(th, d):
    
    # remember: th[0] =  3.11795084
    #           th[1] = -0.05637406
    #           th[2] =  0.10877902
    
    temp = []
    
    X = get_X(d)
    
    for x in X:
        result = 0
        result = th[0] + th[1]*x[1] + th[2]*x[2]
        temp.append(result)
        
    return temp
    

In [299]:
train_ratings = apply_new_model(a, data_1)
train_predictions = np.full((len(train_ratings),1),np.mean(train_ratings))

train_MSE = get_MSE(train_ratings, train_predictions)
train_MSE

array([0.06477346])

In [302]:
test_ratings = apply_new_model(a, data_2)
test_predictions = np.full((len(test_ratings),1),np.mean(test_ratings))

test_MSE = get_MSE(test_ratings, test_predictions)
test_MSE

array([0.05888718])

In [310]:
################################################################
#               ANSWER FOR QUESTION 4                 #
################################################################

print("Training set MSE: %s" % train_MSE)
print("Test set MSE: %s" % test_MSE)

Training set MSE: [0.06477346]
Test set MSE: [0.05888718]


##################################################################### <br>
                           Question 5 <br>#####################################################################

In [304]:
# Shuffle the contents of the original dataset into a new dataset
random.shuffle(data)

In [305]:
# Split the new dataset in half
shuffled_1 = data[:len(data)//2]
shuffled_2 = data[len(data)//2:]

In [306]:
# Get MSE for new training set

shuffled_1_ratings = apply_new_model(a, shuffled_1)
shuffled_1_predictions = np.full((len(shuffled_1_ratings),1),np.mean(shuffled_1_ratings))

shuffled_1_MSE = get_MSE(shuffled_1_ratings, shuffled_1_predictions)
shuffled_1_MSE

array([0.0619843])

In [307]:
# Get MSE for new test set

shuffled_2_ratings = apply_new_model(a, shuffled_2)
shuffled_2_predictions = np.full((len(shuffled_2_ratings),1),np.mean(shuffled_2_ratings))

shuffled_2_MSE = get_MSE(shuffled_2_ratings, shuffled_2_predictions)
shuffled_2_MSE

array([0.06583642])

In [308]:
# Display training and test MSE

print("Training set MSE: %s" % shuffled_1_MSE)
print("Test set MSE: %s" % shuffled_2_MSE)

Training set MSE: [0.0619843]
Test set MSE: [0.06583642]


##################################################################### <br>
                           Question 6 <br>#####################################################################

In [150]:
# Shuffle dataset once more
random.shuffle(data)

In [151]:
#data

In [152]:
# Get all features into separate lists to combine next
review_taste = [d['review/taste'] for d in data]
review_app = [d['review/appearance'] for d in data]
review_ar = [d['review/aroma'] for d in data]
review_pa = [d['review/palate'] for d in data]
review_overall = [d['review/overall'] for d in data]

In [153]:
# Combine all lists into one in order: taste, appearance, aroma, palate, overall

X = []
X = list(zip(review_taste, review_app, review_ar, review_pa, review_overall))
#X

In [183]:
# labels for if beer/style is Hefeweizen

y = ["Hefeweizen" in d['beer/style'] for d in data]
#y

In [155]:
# Split data into training and test set again
X_train = X[:len(X)//2]
y_train = y[:len(y)//2]

X_test = X[len(X)//2:]
y_test = y[len(y)//2:]

In [156]:
# SVM
clf = svm.SVC(C=1000, kernel='linear')
clf.fit(X_train, y_train)

SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [157]:
train_predictions = clf.predict(X_train)
test_predictions = clf.predict(X_test)

In [158]:
# Display train_predictions
train_predictions

array([False, False, False, ..., False, False, False])

In [159]:
# Display test_predictions
test_predictions

array([False, False, False, ..., False, False, False])

In [160]:
# Correctness
correct_train = (train_predictions == y_train)
correct_test = (test_predictions == y_test)

In [161]:
# Accuracy
trainAcc = sum(correct_train) / len(correct_train)
testAcc = sum(correct_test) / len(correct_test)

In [182]:
# Answer to question 6

print("Training accuracy: %s" % trainAcc)
print("Test accuracy: %s" % testAcc)

Training accuracy: 0.98732
Test accuracy: 0.98796


##################################################################### <br>
                           Question 7 <br>#####################################################################

In [163]:
# Shuffle dataset once more
random.shuffle(data)

In [164]:
#data

In [165]:
# Get all features into separate lists to combine next
review_taste = [d['review/taste'] for d in data]
review_app = [d['review/appearance'] for d in data]
review_aroma = [d['review/aroma'] for d in data]
beer_ABV = [d['beer/ABV'] for d in data]
review_overall = [d['review/overall'] for d in data]

In [166]:
# Combine all lists into one in order: taste, appearance, aroma, palate, overall

my_X = []
my_X = list(zip(review_taste, review_app, review_aroma, beer_ABV, review_overall))
#my_X

In [167]:
# labels for if beer/style is Hefeweizen

my_y = ["Hefeweizen" in d['beer/style'] for d in data]
#my_y

In [168]:
# Split data into training and test set again
my_X_train = my_X[:len(X)//2]
my_y_train = my_y[:len(y)//2]

my_X_test = my_X[len(X)//2:]
my_y_test = my_y[len(y)//2:]

In [169]:
# SVM
clf = svm.SVC(C=1000, kernel='linear')
clf.fit(my_X_train, my_y_train)

SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [170]:
my_train_predictions = clf.predict(my_X_train)
my_test_predictions = clf.predict(my_X_test)

In [171]:
# Display train_predictions
my_train_predictions

array([False, False, False, ..., False, False, False])

In [172]:
# Display test_predictions
my_test_predictions

array([False, False, False, ..., False, False, False])

In [173]:
# Correctness
my_correct_train = (my_train_predictions == my_y_train)
my_correct_test = (my_test_predictions == my_y_test)

In [174]:
# Accuracy
myTrainAcc = sum(my_correct_train) / len(my_correct_train)
myTestAcc = sum(my_correct_test) / len(my_correct_test)

In [175]:
# Display accuracies for training and test sets
print("Training accuracy: %s" % myTrainAcc)
print("Test accuracy: %s" % myTestAcc)

Training accuracy: 0.98764
Test accuracy: 0.98764


##################################################################### <br>
                           Question 8 <br>#####################################################################

In [176]:
# Check accuracy for different values of "c"

In [177]:
# Function for SVM
def get_accuracy(c):
    clf = svm.SVC(C=c, kernel='linear')
    clf.fit(my_X_train, my_y_train)
    
    my_train_predictions = clf.predict(my_X_train)
    my_test_predictions = clf.predict(my_X_test)
    
    
    # Correctness
    my_correct_train = (my_train_predictions == my_y_train)
    my_correct_test = (my_test_predictions == my_y_test)
    
    # Accuracy
    myTrainAcc = sum(my_correct_train) / len(my_correct_train)
    myTestAcc = sum(my_correct_test) / len(my_correct_test)
    
    # Display accuracies for training and test sets
    print("Training accuracy: %s" % myTrainAcc)
    print("Test accuracy: %s" % myTestAcc)

In [178]:
# c = 0.1
get_accuracy(0.1)

Training accuracy: 0.98764
Test accuracy: 0.98764


In [179]:
# c = 10
get_accuracy(10)

Training accuracy: 0.98764
Test accuracy: 0.98764


In [180]:
# c = 1000
get_accuracy(1000)

Training accuracy: 0.98764
Test accuracy: 0.98764


In [181]:
# c = 10,000
get_accuracy(10000)

Training accuracy: 0.98764
Test accuracy: 0.98764
