In [110]:
# Imports
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.optimize
import random
from sklearn import svm
import ast

#import patsy
#import statsmodels.api as sm
#import scipy.stats as stats
#from scipy.stats import ttest_ind, chisquare, normaltest

In [111]:
import urllib.request
def parseData(fname):
	for l in urllib.request.urlopen(fname):
		yield eval(l)
data = list(parseData("http://jmcauley.ucsd.edu/cse258/data/beer/beer_50000.json"))

In [186]:
# data
####

In [199]:
lst1 = []
one_star_ratings = 0
two_star_ratings = 0
three_star_ratings = 0
four_star_ratings = 0
five_star_ratings = 0

for i in data:
    for x,y in i.items():
        if x == "review/taste":
            lst1.append(y)
            
for i in lst1:
    if i >= 1.0 and i < 2.0:
        one_star_ratings = one_star_ratings + 1
    elif i >= 2.0 and i < 3.0:
        two_star_ratings = two_star_ratings + 1
    elif i >= 3.0 and i < 4.0:
        three_star_ratings = three_star_ratings + 1
    elif i >= 4.0 and i < 5.0:
        four_star_ratings = four_star_ratings + 1
    elif i >= 5.0:
        five_star_ratings = five_star_ratings + 1
        

#######################################################################        
######                     QUESTION 1                           
#######################################################################

In [200]:
print("# of one star ratings: %s" % one_star_ratings)  # of 1 star ratings = 201
print("# of two star ratings: %s" % two_star_ratings)  # of 2 star ratings = 1099
print("# of three star ratings: %s" % three_star_ratings)  # of 3 star ratings = 4137
print("# of four star ratings: %s" % four_star_ratings)  # of 3 star ratings = 4137
print("# of five star ratings: %s" % five_star_ratings)  # of 3 star ratings = 4137

# of one star ratings: 554
# of two star ratings: 2723
# of three star ratings: 12934
# of four star ratings: 29458
# of five star ratings: 4331


#######################################################################        
######                      QUESTION 2                           #
#######################################################################        

In [216]:
data

[{'review/appearance': 4.0,
  'beer/style': 'American IPA',
  'review/palate': 4.0,
  'review/taste': 4.0,
  'beer/name': 'Founders Centennial IPA',
  'review/timeUnix': 1192673934,
  'beer/ABV': 7.2,
  'beer/beerId': '5441',
  'beer/brewerId': '1199',
  'review/timeStruct': {'isdst': 0,
   'mday': 18,
   'hour': 2,
   'min': 18,
   'sec': 54,
   'mon': 10,
   'year': 2007,
   'yday': 291,
   'wday': 3},
  'review/overall': 4.0,
  'review/text': "Purchased at Merchant's Fine Wine in Dearborn last week. This poured honey golden in the glass, clear with a thin off-white head. Slow but steady stream of small bubble carbonation looks inviting. The head quickly spreads out to thinly coat the surface with a good ring and lacing. Smells very hoppy, banana, cantaloupe, vanilla, spice. Taste is dry with a flash of tartness, bitter, hoppy impressions are pronounced but not over the top, a nice drinking IPA. Mouthfeel was smooth with a lingering ginger-hoppy aftertaste. A swirl produces a regener

In [218]:
# Get all beers (including mulitple occurances) into a list

list_of_all_beers = [d['beer/name'] for d in data]

In [219]:
# Print out all beers including multiple occurances

list_of_all_beers

['Founders Centennial IPA',
 'Founders Pale Ale',
 "King Don's Original Pumpkin Ale",
 'Trafalgar Celebration Ale',
 'D.O.R.I.S. The Destroyer Double Imperial Stout',
 'Barrel Aged Smoke (Smoked Porter)',
 'Founders Dirty Bastard',
 'Hakim Stout',
 'Colón Light',
 'Founders Curmudgeon (Old Ale)',
 'Founders Double Trouble',
 'Weltenburger Kloster Asam-Bock',
 'Benchwarmer Porter',
 'Barrel Aged Naked Evil',
 'Tall Tale Pale Ale',
 'Kirkland Signature German Style Lager',
 'Founders Harvest Ale',
 'Mean Manalishi Double I.P.A.',
 'Stoudts Winter Ale (2009-2010)',
 'Puget Sound Porter',
 'Smooth Hoperator',
 'Founders Pale Ale',
 'Lezajsk 1525 Legendary Premium Lager',
 'Aecht Schlenkerla Rauchbier Märzen',
 'Founders Dirty Bastard',
 'Founders Backwoods Bastard',
 "Hop Master's Abbey Belgian-Style Double IPA",
 'Founders Breakfast Stout',
 'Pilsner Urquell',
 'Founders Nemesis 2009',
 'Founders Dirty Bastard',
 'Stoudts Winter Ale (2009-2010)',
 "Stoudt's Fat Dog Stout",
 "Stoudt's Ba

In [220]:
unique_list = set(list_of_all_beers)

In [221]:
unique_list

{'Pierpont India Pale Ale',
 'St. Alphonzo',
 'KB Grand Cru 2010 - Oak Aged Cassis',
 'Primus',
 'Left Coast Pale Ale',
 'Scarampola Nivura',
 'Harboe Pilsner',
 'Cleopatra',
 'Cucapá Honey',
 'Ländlegold Premium',
 'Amsterdam Navigator',
 'Wee Heavy Scotch Ale',
 'Flying Aces Ale',
 "McGale's Pale Ale",
 'Golden Orchid',
 "Stoudt's Abbey Triple (750ml Release)",
 'Champion Reserve IPA',
 "Stoudt's Blonde Double MaiBock",
 'Schorschbräu Schorschbock 40%',
 'Black Magic',
 'Belgoo Magus',
 "Frankenlou's IPA",
 'Cucapá Lowrider Ale',
 'Belgoo Luppo',
 'Ombibulous Double IPA',
 'Aecht Schlenkerla Rauchbier Märzen',
 'Sub Zero',
 'Zona Brewing Helles',
 'Swamp Fox IPA',
 'Classic Blonde',
 'Old Brick Irish Amber Ale',
 'Colón Negra',
 'Pacific Pilsner',
 "Tom Wood's Harvest Bitter",
 'Haleighs Honey Brown',
 "Farmer Ted's Cream Ale",
 'Hooker',
 'Copper Crow IPA',
 'Braveheart Beir',
 'Känguruh Bernsteintrunk',
 "D'n Osse Frater Bokbier",
 'BMF Stout',
 "Cutt's Ale",
 'White Chapel 

In [222]:
len(unique_list)

1872

In [223]:
beers_unique = [[x,list_of_all_beers.count(x)] for x in set(list_of_all_beers)]

In [224]:
beers_unique

[['Pierpont India Pale Ale', 3],
 ['St. Alphonzo', 2],
 ['KB Grand Cru 2010 - Oak Aged Cassis', 1],
 ['Primus', 4],
 ['Left Coast Pale Ale', 11],
 ['Scarampola Nivura', 1],
 ['Harboe Pilsner', 2],
 ['Cleopatra', 1],
 ['Cucapá Honey', 32],
 ['Ländlegold Premium', 1],
 ['Amsterdam Navigator', 4],
 ['Wee Heavy Scotch Ale', 17],
 ['Flying Aces Ale', 5],
 ["McGale's Pale Ale", 1],
 ['Golden Orchid', 1],
 ["Stoudt's Abbey Triple (750ml Release)", 55],
 ['Champion Reserve IPA', 18],
 ["Stoudt's Blonde Double MaiBock", 175],
 ['Schorschbräu Schorschbock 40%', 3],
 ['Black Magic', 1],
 ['Belgoo Magus', 41],
 ["Frankenlou's IPA", 8],
 ['Cucapá Lowrider Ale', 8],
 ['Belgoo Luppo', 6],
 ['Ombibulous Double IPA', 3],
 ['Aecht Schlenkerla Rauchbier Märzen', 889],
 ['Sub Zero', 1],
 ['Zona Brewing Helles', 1],
 ['Swamp Fox IPA', 41],
 ['Classic Blonde', 1],
 ['Old Brick Irish Amber Ale', 3],
 ['Colón Negra', 4],
 ['Pacific Pilsner', 1],
 ["Tom Wood's Harvest Bitter", 2],
 ['Haleighs Honey Brown

In [244]:
len(beers_unique)

1872

In [247]:
# Dictionary of all beers with at least 5 reviews (unique)

diction1 = {}
for a in beers_unique:
    if a[1] >= 5:
        diction1[a[0]] = a[1]
        
diction1

{'Left Coast Pale Ale': 11,
 'Cucapá Honey': 32,
 'Wee Heavy Scotch Ale': 17,
 'Flying Aces Ale': 5,
 "Stoudt's Abbey Triple (750ml Release)": 55,
 'Champion Reserve IPA': 18,
 "Stoudt's Blonde Double MaiBock": 175,
 'Belgoo Magus': 41,
 "Frankenlou's IPA": 8,
 'Cucapá Lowrider Ale': 8,
 'Belgoo Luppo': 6,
 'Aecht Schlenkerla Rauchbier Märzen': 889,
 'Swamp Fox IPA': 41,
 "Farmer Ted's Cream Ale": 8,
 'Hooker': 6,
 'Weltenburger Kloster Oktober-Festbier': 7,
 'Zhiguly Grande 9,5': 12,
 'Horse Piss Beer': 55,
 'Trafalgar Korruptor': 15,
 'Bourbon Barrel Rye Porter': 7,
 'Wheat Beer': 6,
 'IPA Belge': 7,
 'Dixie Crystal Beer': 6,
 'Amber Ale - German Style Altbier': 15,
 'Emmerdale': 10,
 'Caldera Ginger Beer': 9,
 'The Big O': 15,
 'Founders Crystal Rye Persuasion': 5,
 'EZ Ryeder': 15,
 'Black Gold': 10,
 'La Récompense': 24,
 'Pike India Pale Ale': 198,
 'Founders Barrel Aged Imperial Stout': 29,
 'Ironwood Dark': 5,
 'Sedm KulÃ\xad (13% SpeciálnÃ\xad Pivo Polotmavé )': 6,
 'Dub

In [251]:
len(diction1)

647

In [249]:
# Dictionary of all beers and their review/taste

diction2 = {}
for i in data:
    for a,b in i.items():
        for c,d in i.items():
            if a == 'beer/name':
                if c == 'review/taste':
                    diction2[b] = d
diction2

{'Founders Centennial IPA': 4.0,
 'Founders Pale Ale': 4.0,
 "King Don's Original Pumpkin Ale": 5.0,
 'Trafalgar Celebration Ale': 4.0,
 'D.O.R.I.S. The Destroyer Double Imperial Stout': 5.0,
 'Barrel Aged Smoke (Smoked Porter)': 4.0,
 'Founders Dirty Bastard': 4.0,
 'Hakim Stout': 3.0,
 'Colón Light': 2.5,
 'Founders Curmudgeon (Old Ale)': 4.5,
 'Founders Double Trouble': 4.0,
 'Weltenburger Kloster Asam-Bock': 4.5,
 'Benchwarmer Porter': 4.0,
 'Barrel Aged Naked Evil': 5.0,
 'Tall Tale Pale Ale': 4.0,
 'Kirkland Signature German Style Lager': 3.5,
 'Founders Harvest Ale': 4.0,
 'Mean Manalishi Double I.P.A.': 4.5,
 'Stoudts Winter Ale (2009-2010)': 3.5,
 'Puget Sound Porter': 4.0,
 'Smooth Hoperator': 2.5,
 'Lezajsk 1525 Legendary Premium Lager': 3.5,
 'Aecht Schlenkerla Rauchbier Märzen': 4.5,
 'Founders Backwoods Bastard': 4.5,
 "Hop Master's Abbey Belgian-Style Double IPA": 4.0,
 'Founders Breakfast Stout': 4.5,
 'Pilsner Urquell': 4.0,
 'Founders Nemesis 2009': 3.5,
 "Stoudt's 

In [252]:
diction3 = {}
for a,b in diction1.items():
    count = 0
    for c,d in diction2.items():
        if c == a:
            count += d
    diction3[a] = count
    
diction3

{'Left Coast Pale Ale': 2.5,
 'Cucapá Honey': 3.5,
 'Wee Heavy Scotch Ale': 3.5,
 'Flying Aces Ale': 3.5,
 "Stoudt's Abbey Triple (750ml Release)": 4.0,
 'Champion Reserve IPA': 4.0,
 "Stoudt's Blonde Double MaiBock": 3.5,
 'Belgoo Magus': 3.5,
 "Frankenlou's IPA": 1.0,
 'Cucapá Lowrider Ale': 4.0,
 'Belgoo Luppo': 3.0,
 'Aecht Schlenkerla Rauchbier Märzen': 4.5,
 'Swamp Fox IPA': 3.5,
 "Farmer Ted's Cream Ale": 4.0,
 'Hooker': 3.5,
 'Weltenburger Kloster Oktober-Festbier': 3.5,
 'Zhiguly Grande 9,5': 3.5,
 'Horse Piss Beer': 2.0,
 'Trafalgar Korruptor': 3.5,
 'Bourbon Barrel Rye Porter': 4.0,
 'Wheat Beer': 3.0,
 'IPA Belge': 4.0,
 'Dixie Crystal Beer': 3.0,
 'Amber Ale - German Style Altbier': 3.5,
 'Emmerdale': 3.0,
 'Caldera Ginger Beer': 4.0,
 'The Big O': 3.0,
 'Founders Crystal Rye Persuasion': 4.5,
 'EZ Ryeder': 4.5,
 'Black Gold': 5.0,
 'La Récompense': 3.0,
 'Pike India Pale Ale': 4.0,
 'Founders Barrel Aged Imperial Stout': 4.5,
 'Ironwood Dark': 2.5,
 'Sedm KulÃ\xad (13

In [253]:
diction4 = {}
for a,b in diction1.items():
    for c,d in diction3.items():
        if c == a:
            diction4[a] = d / b
            
diction4

{'Left Coast Pale Ale': 0.22727272727272727,
 'Cucapá Honey': 0.109375,
 'Wee Heavy Scotch Ale': 0.20588235294117646,
 'Flying Aces Ale': 0.7,
 "Stoudt's Abbey Triple (750ml Release)": 0.07272727272727272,
 'Champion Reserve IPA': 0.2222222222222222,
 "Stoudt's Blonde Double MaiBock": 0.02,
 'Belgoo Magus': 0.08536585365853659,
 "Frankenlou's IPA": 0.125,
 'Cucapá Lowrider Ale': 0.5,
 'Belgoo Luppo': 0.5,
 'Aecht Schlenkerla Rauchbier Märzen': 0.005061867266591676,
 'Swamp Fox IPA': 0.08536585365853659,
 "Farmer Ted's Cream Ale": 0.5,
 'Hooker': 0.5833333333333334,
 'Weltenburger Kloster Oktober-Festbier': 0.5,
 'Zhiguly Grande 9,5': 0.2916666666666667,
 'Horse Piss Beer': 0.03636363636363636,
 'Trafalgar Korruptor': 0.23333333333333334,
 'Bourbon Barrel Rye Porter': 0.5714285714285714,
 'Wheat Beer': 0.5,
 'IPA Belge': 0.5714285714285714,
 'Dixie Crystal Beer': 0.5,
 'Amber Ale - German Style Altbier': 0.23333333333333334,
 'Emmerdale': 0.3,
 'Caldera Ginger Beer': 0.44444444444444

In [255]:
# Find highest average rate beer (review/taste)
maximum = 0
for a,b in diction4.items():
    if b >= maximum:
        maximum = b
        

1.0

In [256]:
# Highest rated beers
temp1 = []
for c,d in diction4.items():
    if d == maximum:
        temp1.append(c)
        
temp1

['Benny Brew Hopenstein',
 'Porter Porter',
 'Lost Sailor IPA',
 'Founders Sumatra Mountain Brown']

In [257]:
diction4['Benny Brew Hopenstein']

1.0

In [258]:
diction4['Porter Porter']

1.0

In [259]:
diction4['Lost Sailor IPA']

1.0

In [260]:
diction4['Founders Sumatra Mountain Brown']

1.0

In [124]:
len(data)

50000

In [125]:
lst3 = []
for i in range(len(data)):
    lst3.append(1)
    
len(lst3)

50000

In [126]:
lst4 = []

for i in data:
    for x,y in i.items():
        if x == 'beer/style':
            lst4.append(y)

#lst4


In [127]:
lst6 = []
for i in lst4:
    if i == 'Hefeweizen':
        lst6.append(1)
    else:
        lst6.append(0)
        
lst6.count(1)

618

In [128]:
lst5 = []
for i in data:
    for x,y in i.items():
        if x == 'beer/ABV':
            lst5.append(y)
     
    
#lst5

In [215]:
X = list(zip(lst3,lst6,lst5))
X

[(1, 1, 5.0),
 (1, 0, 6.2),
 (1, 0, 6.5),
 (1, 0, 5.0),
 (1, 0, 7.7),
 (1, 0, 4.7),
 (1, 0, 4.7),
 (1, 0, 4.7),
 (1, 0, 4.7),
 (1, 0, 4.7),
 (1, 0, 4.7),
 (1, 0, 4.7),
 (1, 0, 4.7),
 (1, 0, 4.7),
 (1, 0, 7.2),
 (1, 0, 7.2),
 (1, 0, 5.6),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 7.4),
 (1, 0, 5.5),
 (1, 0, 5.5),
 (1, 0, 5.5),
 (1, 0, 5.5),
 (1, 0, 5.5),
 (1, 0, 5.5),
 (1, 0, 5.5),
 (1, 0, 5.5),
 (1, 0, 5.5),
 (1, 0, 5.5),
 (1, 0, 5.5),
 (1, 0, 5.5),
 (1, 0

In [130]:
y = [d['review/taste'] for d in data]

In [131]:
len(y)

50000

In [132]:
theta,residuals,rank,s = np.linalg.lstsq(X, y)

D:\ProgramFiles\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


#######################################################################        
                     QUESTION 3            
#######################################################################


####### Not entirely sure about the answers. Will have to come back to this one.
theta_0 = indicates the average review/taste. <br>
theta_1 = indicates the difference between the average review/taste when beer/ABV is 0. <br>
theta_2 = indicates the difference between the average review/taste when beer is not Hefeweizen (0).  <br>

In [214]:
# Theta values for theta 0, theta 1, and theta 2
print("theta_0: %s" % theta[0])
print("theta_1: %s" % theta[1])
print("theta_2: %s" % theta[2])

theta_0: 3.1179508424741784
theta_1: -0.05637405770379309
theta_2: 0.10877901639208253


##################################################################### <br>
                           Question 4 <br>#####################################################################

In [134]:
# Split the original dataset in half
data_1 = data[:len(data)//2] # training set
data_2 = data[len(data)//2:] # test set

In [135]:
def get_col_1(d):
    temp_lst1 = []
    
    for i in range(len(d)):
        temp_lst1.append(1)
        
    return temp_lst1

In [136]:
def get_col_2(d):
    temp_lst = []

    for i in d:
        for x,y in i.items():
            if x == 'beer/style':
                temp_lst.append(y)

    temp_lst2 = []
    for i in temp_lst:
        if i == 'Hefeweizen':
            temp_lst2.append(1)
        else:
            temp_lst2.append(0)
    
    return temp_lst2
        
      

In [137]:
def get_col_3(d):
    temp_lst = []
    
    for i in d:
        for x,y in i.items():
            if x == 'beer/ABV':
                temp_lst.append(y)
     
    return temp_lst

In [138]:
def get_X(d):
    
    X = list(zip(get_col_1(d), get_col_2(d), get_col_3(d)))
    
    return X
    

In [139]:
def get_y(d):
    
    y = [da['review/taste'] for da in d]
    
    return y

In [140]:
def get_thetas(d):
    
    X = get_X(d)
    y = get_y(d)
    
    theta,residuals,rank,s = np.linalg.lstsq(X, y)
    
    return theta

In [141]:
# verify get functions work on original data
a = get_thetas(data)
a

D:\ProgramFiles\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


array([ 3.11795084, -0.05637406,  0.10877902])

In [142]:
def get_MSE(ratings, predictions):
    
    mse = 0
    
    for r, p in zip(ratings, predictions):
        mse = mse + (r - p)**2
        
    return (mse / len(ratings))

In [143]:
def get_ratings(d):
    tmp_lst = []
    
    for i in d:
        for x,y in i.items():
            if x == 'review/taste':
                tmp_lst.append(y)
                
    return tmp_lst

In [144]:
# Get MSE for training set

train_ratings = get_ratings(data_1)
train_predictions = np.full((len(train_ratings),1),np.mean(train_ratings))

train_MSE = get_MSE(train_ratings, train_predictions)
train_MSE # MSE for training set

array([0.55835536])

In [145]:
# Get MSE for test set

test_ratings = get_ratings(data_2)
test_predictions = np.full((len(test_ratings),1),np.mean(test_ratings))

test_MSE = get_MSE(test_ratings, test_predictions)
test_MSE # MSE for test set

array([0.46844391])

##################################################################### <br>
                           Question 5 <br>#####################################################################

In [146]:
# Shuffle the contents of the original dataset into a new dataset
random.shuffle(data)

In [147]:
# Split the new dataset in half
shuffled_1 = data[:len(data)//2]
shuffled_2 = data[len(data)//2:]

In [148]:
# Get MSE for new training set

shuffled_1_ratings = get_ratings(shuffled_1)
shuffled_1_predictions = np.full((len(shuffled_1_ratings),1),np.mean(shuffled_1_ratings))

shuffled_1_MSE = get_MSE(shuffled_1_ratings, shuffled_1_predictions)
shuffled_1_MSE

array([0.52173536])

In [149]:
# Get MSE for new test set

shuffled_2_ratings = get_ratings(shuffled_2)
shuffled_2_predictions = np.full((len(shuffled_2_ratings),1),np.mean(shuffled_2_ratings))

shuffled_2_MSE = get_MSE(shuffled_2_ratings, shuffled_2_predictions)
shuffled_2_MSE

array([0.50540445])

##################################################################### <br>
                           Question 6 <br>#####################################################################

In [150]:
# Shuffle dataset once more
random.shuffle(data)

In [151]:
#data

In [152]:
# Get all features into separate lists to combine next
review_taste = [d['review/taste'] for d in data]
review_app = [d['review/appearance'] for d in data]
review_ar = [d['review/aroma'] for d in data]
review_pa = [d['review/palate'] for d in data]
review_overall = [d['review/overall'] for d in data]

In [153]:
# Combine all lists into one in order: taste, appearance, aroma, palate, overall

X = []
X = list(zip(review_taste, review_app, review_ar, review_pa, review_overall))
#X

In [183]:
# labels for if beer/style is Hefeweizen

y = ["Hefeweizen" in d['beer/style'] for d in data]
#y

In [155]:
# Split data into training and test set again
X_train = X[:len(X)//2]
y_train = y[:len(y)//2]

X_test = X[len(X)//2:]
y_test = y[len(y)//2:]

In [156]:
# SVM
clf = svm.SVC(C=1000, kernel='linear')
clf.fit(X_train, y_train)

SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [157]:
train_predictions = clf.predict(X_train)
test_predictions = clf.predict(X_test)

In [158]:
# Display train_predictions
train_predictions

array([False, False, False, ..., False, False, False])

In [159]:
# Display test_predictions
test_predictions

array([False, False, False, ..., False, False, False])

In [160]:
# Correctness
correct_train = (train_predictions == y_train)
correct_test = (test_predictions == y_test)

In [161]:
# Accuracy
trainAcc = sum(correct_train) / len(correct_train)
testAcc = sum(correct_test) / len(correct_test)

In [182]:
# Answer to question 6

print("Training accuracy: %s" % trainAcc)
print("Test accuracy: %s" % testAcc)

Training accuracy: 0.98732
Test accuracy: 0.98796


##################################################################### <br>
                           Question 7 <br>#####################################################################

In [163]:
# Shuffle dataset once more
random.shuffle(data)

In [164]:
#data

In [165]:
# Get all features into separate lists to combine next
review_taste = [d['review/taste'] for d in data]
review_app = [d['review/appearance'] for d in data]
review_aroma = [d['review/aroma'] for d in data]
beer_ABV = [d['beer/ABV'] for d in data]
review_overall = [d['review/overall'] for d in data]

In [166]:
# Combine all lists into one in order: taste, appearance, aroma, palate, overall

my_X = []
my_X = list(zip(review_taste, review_app, review_aroma, beer_ABV, review_overall))
#my_X

In [167]:
# labels for if beer/style is Hefeweizen

my_y = ["Hefeweizen" in d['beer/style'] for d in data]
#my_y

In [168]:
# Split data into training and test set again
my_X_train = my_X[:len(X)//2]
my_y_train = my_y[:len(y)//2]

my_X_test = my_X[len(X)//2:]
my_y_test = my_y[len(y)//2:]

In [169]:
# SVM
clf = svm.SVC(C=1000, kernel='linear')
clf.fit(my_X_train, my_y_train)

SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [170]:
my_train_predictions = clf.predict(my_X_train)
my_test_predictions = clf.predict(my_X_test)

In [171]:
# Display train_predictions
my_train_predictions

array([False, False, False, ..., False, False, False])

In [172]:
# Display test_predictions
my_test_predictions

array([False, False, False, ..., False, False, False])

In [173]:
# Correctness
my_correct_train = (my_train_predictions == my_y_train)
my_correct_test = (my_test_predictions == my_y_test)

In [174]:
# Accuracy
myTrainAcc = sum(my_correct_train) / len(my_correct_train)
myTestAcc = sum(my_correct_test) / len(my_correct_test)

In [175]:
# Display accuracies for training and test sets
print("Training accuracy: %s" % myTrainAcc)
print("Test accuracy: %s" % myTestAcc)

Training accuracy: 0.98764
Test accuracy: 0.98764


##################################################################### <br>
                           Question 8 <br>#####################################################################

In [176]:
# Check accuracy for different values of "c"

In [177]:
# Function for SVM
def get_accuracy(c):
    clf = svm.SVC(C=c, kernel='linear')
    clf.fit(my_X_train, my_y_train)
    
    my_train_predictions = clf.predict(my_X_train)
    my_test_predictions = clf.predict(my_X_test)
    
    
    # Correctness
    my_correct_train = (my_train_predictions == my_y_train)
    my_correct_test = (my_test_predictions == my_y_test)
    
    # Accuracy
    myTrainAcc = sum(my_correct_train) / len(my_correct_train)
    myTestAcc = sum(my_correct_test) / len(my_correct_test)
    
    # Display accuracies for training and test sets
    print("Training accuracy: %s" % myTrainAcc)
    print("Test accuracy: %s" % myTestAcc)

In [178]:
# c = 0.1
get_accuracy(0.1)

Training accuracy: 0.98764
Test accuracy: 0.98764


In [179]:
# c = 10
get_accuracy(10)

Training accuracy: 0.98764
Test accuracy: 0.98764


In [180]:
# c = 1000
get_accuracy(1000)

Training accuracy: 0.98764
Test accuracy: 0.98764


In [181]:
# c = 10,000
get_accuracy(10000)

Training accuracy: 0.98764
Test accuracy: 0.98764
